image: node:carbon

stages:
  - test
  - package

services:
  - docker:dind

before_script:
  - printenv

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

push-to-npm:
  stage: package
  script:
    - npm install --prefix $SOLUTION_PATH -g
    - npm publish $SOLUTION_PATH --registry=$NPM_SOURCE_URL
  only:
    refs:
      - master
    variables:
      - $NPM_SOURCE_URL && $SOLUTION_PATH

test:
  stage: test
  script:
    - npm install --prefix $SOLUTION_PATH
    - npm test --prefix $PROJECT_PATH_TEST
  only:
    variables:
      - $PROJECT_PATH_TEST && $SOLUTION_PATH
